### ISSUE TITLE
Unable to Implement yoloV3 on Video

### ISSUE THREAD

**Issue by mananhfz** [AyushExel/Detectx-Yolo-V3#2]
When I try to run the model on the video I see this error.

```
Traceback (most recent call last):
  File "detect_video.py", line 110, in <module>
    img, orig_im, dim = prepare_input(frame, inp_dim)
  File "detect_video.py", line 26, in prepare_input
    img = (resize_img(orig_im, (inp_dim, inp_dim)))
NameError: name 'resize_img' is not defined
```

**Comment by mananhfz** [comment]
I'm getting this error on another video.

```
Traceback (most recent call last):
  File "detect_video.py", line 102, in <module>
    assert cap.isOpened(), 'Cannot capture source'
AssertionError: Cannot capture source
```

**Comment by AyushExel** [comment]
By default, the name of the input video is video.avi. if you're using another video, specify the name in command line of change the video name in the code
